# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/linuxbrew/.linuxbrew/Cellar/cmake/3.27.7/bin/cmake

# The command to remove a file.
RM = /home/linuxbrew/.linuxbrew/Cellar/cmake/3.27.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspace/vDNN

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspace/vDNN

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.27.7/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/linuxbrew/.linuxbrew/Cellar/cmake/3.27.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/vDNN/CMakeFiles /workspace/vDNN//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/vDNN/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named neural_net_vdnn.out

# Build rule for target.
neural_net_vdnn.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 neural_net_vdnn.out
.PHONY : neural_net_vdnn.out

# fast build rule for target.
neural_net_vdnn.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_vdnn.out.dir/build.make CMakeFiles/neural_net_vdnn.out.dir/build
.PHONY : neural_net_vdnn.out/fast

#=============================================================================
# Target rules for targets named mnist_test.out

# Build rule for target.
mnist_test.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mnist_test.out
.PHONY : mnist_test.out

# fast build rule for target.
mnist_test.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mnist_test.out.dir/build.make CMakeFiles/mnist_test.out.dir/build
.PHONY : mnist_test.out/fast

#=============================================================================
# Target rules for targets named alexnet_test.out

# Build rule for target.
alexnet_test.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 alexnet_test.out
.PHONY : alexnet_test.out

# fast build rule for target.
alexnet_test.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alexnet_test.out.dir/build.make CMakeFiles/alexnet_test.out.dir/build
.PHONY : alexnet_test.out/fast

#=============================================================================
# Target rules for targets named vgg_test.out

# Build rule for target.
vgg_test.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vgg_test.out
.PHONY : vgg_test.out

# fast build rule for target.
vgg_test.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vgg_test.out.dir/build.make CMakeFiles/vgg_test.out.dir/build
.PHONY : vgg_test.out/fast

#=============================================================================
# Target rules for targets named slow_conv.out

# Build rule for target.
slow_conv.out: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 slow_conv.out
.PHONY : slow_conv.out

# fast build rule for target.
slow_conv.out/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slow_conv.out.dir/build.make CMakeFiles/slow_conv.out.dir/build
.PHONY : slow_conv.out/fast

src/cnmem.o: src/cnmem.cpp.o
.PHONY : src/cnmem.o

# target to build an object file
src/cnmem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_vdnn.out.dir/build.make CMakeFiles/neural_net_vdnn.out.dir/src/cnmem.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mnist_test.out.dir/build.make CMakeFiles/mnist_test.out.dir/src/cnmem.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alexnet_test.out.dir/build.make CMakeFiles/alexnet_test.out.dir/src/cnmem.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vgg_test.out.dir/build.make CMakeFiles/vgg_test.out.dir/src/cnmem.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slow_conv.out.dir/build.make CMakeFiles/slow_conv.out.dir/src/cnmem.cpp.o
.PHONY : src/cnmem.cpp.o

src/cnmem.i: src/cnmem.cpp.i
.PHONY : src/cnmem.i

# target to preprocess a source file
src/cnmem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_vdnn.out.dir/build.make CMakeFiles/neural_net_vdnn.out.dir/src/cnmem.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mnist_test.out.dir/build.make CMakeFiles/mnist_test.out.dir/src/cnmem.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alexnet_test.out.dir/build.make CMakeFiles/alexnet_test.out.dir/src/cnmem.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vgg_test.out.dir/build.make CMakeFiles/vgg_test.out.dir/src/cnmem.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slow_conv.out.dir/build.make CMakeFiles/slow_conv.out.dir/src/cnmem.cpp.i
.PHONY : src/cnmem.cpp.i

src/cnmem.s: src/cnmem.cpp.s
.PHONY : src/cnmem.s

# target to generate assembly for a file
src/cnmem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/neural_net_vdnn.out.dir/build.make CMakeFiles/neural_net_vdnn.out.dir/src/cnmem.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mnist_test.out.dir/build.make CMakeFiles/mnist_test.out.dir/src/cnmem.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/alexnet_test.out.dir/build.make CMakeFiles/alexnet_test.out.dir/src/cnmem.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vgg_test.out.dir/build.make CMakeFiles/vgg_test.out.dir/src/cnmem.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/slow_conv.out.dir/build.make CMakeFiles/slow_conv.out.dir/src/cnmem.cpp.s
.PHONY : src/cnmem.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... alexnet_test.out"
	@echo "... mnist_test.out"
	@echo "... neural_net_vdnn.out"
	@echo "... slow_conv.out"
	@echo "... vgg_test.out"
	@echo "... src/cnmem.o"
	@echo "... src/cnmem.i"
	@echo "... src/cnmem.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

